create table if not exists public.company_settings (
  id bigint generated by default as identity primary key,
  company_name text not null default 'ALB APP',
  company_phone text,
  company_address text,
  company_pix text,
  company_logo text,
  updated_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  client_name text not null,
  client_phone text,
  client_address text,
  service_description text,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  status text not null default 'Pendente',
  created_at timestamptz not null default now()
);

create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  service text not null,
  qty numeric(12,2) not null default 1,
  price numeric(12,2) not null default 0,
  subtotal numeric(12,2) generated always as (qty * price) stored
);

create table if not exists public.finance_entries (
  id uuid primary key default gen_random_uuid(),
  entry_date date not null default current_date,
  description text not null,
  type text not null check (type in ('entrada', 'saida')),
  value numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

insert into public.company_settings (id, company_name, company_phone, company_address, company_pix)
values (1, 'ALB APP', '(98) 98147-3574', 'São Luis - MA', '(98) 98147-3574')
on conflict (id) do nothing;
